trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
- name: service_name
  value: cache_warmer
- name: service_name_health_check
  value: cache_warmer_health_check

steps:
- task: SSH@0
  displayName: cleanup
  inputs:
    sshEndpoint: 'ssh_service_server'
    runOptions: 'inline'
    inline: |
      rm -rf /services/$(service_name)
      rm -rf /services/$(service_name_health_check)
      rm -rf /var/log/$(service_name).log
      rm -rf /var/log/$(service_name_health_check).log
      sudo rm -rf /etc/systemd/system/$(service_name).service
      sudo rm -rf /etc/systemd/system/$(service_name_health_check).service
    interactiveSession: true
    readyTimeout: '20000'
    retryCountOnTaskFailure: "3"
- task: SSH@0
  displayName: install requirements on server
  inputs:
    sshEndpoint: 'ssh_service_server'
    runOptions: 'inline'
    inline: |
      apt update && apt upgrade -y
      apt install software-properties-common -y
      sudo add-apt-repository ppa:deadsnakes/ppa -y
      apt install -y python3.11 python3.11-venv python3.11-dev curl build-essential
    interactiveSession: true
    readyTimeout: '20000'
    retryCountOnTaskFailure: "3"
- task: CopyFilesOverSSH@0
  displayName: copy_files_to_service_server
  inputs:
    sshEndpoint: 'ssh_service_server'
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    contents: '**'
    targetFolder: '/services/$(service_name)'
  retryCountOnTaskFailure: "3"
- task: SSH@0
  displayName: build_venv
  inputs:
    sshEndpoint: 'ssh_service_server'
    runOptions: 'inline'
    inline: |
      rm -rf /services/$(service_name)/venv
      python3.11 -m venv /services/$(service_name)/venv
    interactiveSession: true
    readyTimeout: '20000'
    retryCountOnTaskFailure: "3"
- task: SSH@0
  displayName: venv_install_cache_warmer
  inputs:
    sshEndpoint: 'ssh_service_server'
    runOptions: 'inline'
    inline: |
      set -ux
      cd /services/$(service_name)
      source /services/$(service_name)/venv/bin/activate
      pip install --upgrade pip
      pip install .
      pip list
    interactiveSession: true
    readyTimeout: '20000'
    retryCountOnTaskFailure: "3"
- task: SSH@0
  displayName: apply_as_systemd_service_$(service_name)
  inputs:
    sshEndpoint: 'ssh_service_server'
    runOptions: 'inline'
    inline: |
      chmod +x /services/$(service_name)/src/$(service_name)/scheduler.py
      cp /services/$(service_name)/src/$(service_name)/$(service_name).service /etc/systemd/system/$(service_name).service
      sudo systemctl stop $(service_name)
      sudo systemctl daemon-reload
      sudo systemctl start $(service_name)
      sudo systemctl enable $(service_name)
      sudo systemctl --no-pager status $(service_name)
    interactiveSession: true
    readyTimeout: '20000'
    retryCountOnTaskFailure: "3"
- task: SSH@0
  displayName: apply_as_systemd_service_$(service_name_health_check)
  inputs:
    sshEndpoint: 'ssh_service_server'
    runOptions: 'inline'
    inline: |
      chmod +x /services/$(service_name)/src/$(service_name)/scheduler_health_check.py
      cp /services/$(service_name)/src/$(service_name)/$(service_name_health_check).service /etc/systemd/system/$(service_name_health_check).service
      sudo systemctl stop $(service_name_health_check)
      sudo systemctl daemon-reload
      sudo systemctl start $(service_name_health_check)
      sudo systemctl enable $(service_name_health_check)
      sudo systemctl --no-pager status $(service_name_health_check)
    interactiveSession: true
    readyTimeout: '20000'
    retryCountOnTaskFailure: "3"
